version: '3.8'

services:
  web:
    build: ./config/docker-web #dai un nome a questa build
    image: docker-web:1.0 
    container_name: web-${CONTAINER_NAMESPACE:'env'}
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./config/apache:/etc/apache2
      - ./config/php:/usr/local/etc/php
    depends_on:
      - db
      - redis
      - mailhog
    networks:
      - app-network

  db:
    image: mariadb:10.11
    container_name: db-${CONTAINER_NAMESPACE:'env'}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:app_db}
      MYSQL_USER: ${MYSQL_USER:app_user} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:app_pass}
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-${CONTAINER_NAMESPACE:'env'}
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis-${CONTAINER_NAMESPACE:'env'}
    ports:
      - "6379:6379"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog-${CONTAINER_NAMESPACE:'env'}
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
